name: cift_teker_front
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.6.0
  cloud_firestore: ^5.6.0
  firebase_storage: ^12.1.0
  firebase_auth: ^5.7.0
  cloud_functions: ^5.3.0
  cached_network_image: ^3.2.3
  mask_text_input_formatter: ^2.8.0
  path: ^1.9.1
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  http: ^1.6.0
  flutter_secure_storage: ^9.2.4
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  google_maps_flutter: ^2.14.0
  geolocator: ^14.0.2
  web_socket_channel: ^3.0.3
  stomp_dart_client: ^3.0.1
  jwt_decoder: ^2.0.1
  image_picker: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true

  assets:
    - assets/ciftTeker.png
    - assets/grupSurus.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/ciftTeker.png
  min_sdk_android: 21
